# Site settings
title: Marco de Jong
email: info@marco-dejong.nl
description: Marco de Jong - Full Stack Developer & Songwriter. How can I help you?
url: "https://marco-dejong.nl"
twitter_username: marcodejong
google_analytics: G-VL9396KZFV

# Build settings
markdown: kramdown
permalink: none

plugins:
  - jekyll-sitemap
